version: "3"
php-fpm:
    build: install/php-fpm
    ports:
        - 9010:9000
    volumes:
        - .:/var/www/html/
    links:
        - db
nginx:
    build: install/nginx
    ports:
        - 8080:80
    volumes:
        - .:/var/www/html/        
    links:
        - php-fpm
db:
    image: mysql:5.6
    ports:
        - 3308:3306
    environment:
        MYSQL_DATABASE: andrealinfo
        MYSQL_USER: andreal
        MYSQL_PASSWORD: andreal!@#)(*)
        MYSQL_ROOT_PASSWORD: root!@#)(*)
